driver:
  name: vagrant
  vagrantfiles:
    - test/vagrantfile_merge.rb

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  #always_update_cookbooks: true
  product_name: chef

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default-chef12
    provisioner:
      product_version: 12
    run_list:
      - recipe[gamegos-supervisor::test]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: { foo: "bar" }

  - name: default-chef13
    provisioner:
      product_version: 13
    run_list:
      - recipe[gamegos-supervisor::test]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: { foo: "bar" }
